### ISSUE TITLE
好奇数据是怎么整理出来的。。

### ISSUE THREAD

**Issue by axuebin** [Ovilia/lipstick#1]

**Comment by 252860883** [comment]
可能是因为有个超级喜欢买口红的女朋友吧哈哈哈

**Comment by gaocegege** [comment]
@252860883 emmm owner 是女生

**Comment by liuliangsir** [comment]
没有意义的issue，建议关闭

**Comment by Ovilia** [comment]
从各个网站上半自动抓的，颜色是 Sketch 里面选的，因为一般都是图片，然后每个牌子又不太一样，所以懒得写自动化的取色代码 😂

**Comment by Parman-T** [comment]
如果能跳转京东商城链接真就完美了！！
作者辛苦！真的太棒了

**Comment by Ovilia** [comment]
@Parman-T 怕被人说恰饭哈哈

**Comment by 8MiYile** [comment]
> @Parman-T 怕被人说恰饭哈哈

可以丢一个大致的搜索方法，然后让他们自己对比，不就没有恰饭之嫌了嘛，东西是他们自己选的哈哈哈
