### ISSUE TITLE
最近刚弄了个。

### ISSUE THREAD

**Issue by anderpang** [Ovilia/lipstick#20]
https://x.harmay.com/test/lips/

**Comment by Ovilia** [comment]
哇塞，赞诶！

**Comment by anderpang** [comment]
> 哇塞，赞诶！

公司的demo，还不是最终版，555

**Comment by Ovilia** [comment]
这是你一个人做的还是团队一起的？感觉完成度非常高

**Comment by anderpang** [comment]
一个人，我们的前端团队就我一个。



------------------ 原始邮件 ------------------
发件人: "Ovilia"<notifications@github.com>; 
发送时间: 2019年5月22日(星期三) 中午1:16
收件人: "Ovilia/lipstick"<lipstick@noreply.github.com>; 
抄送: "布衣修罗"<anderpang@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Ovilia/lipstick] 最近刚弄了个。 (#20)




这是你一个人做的还是团队一起的？感觉完成度非常高
