### ISSUE TITLE
给项目添加一个运行入口

### ISSUE THREAD

**Issue by JserJser** [Ovilia/lipstick#21]
安装
 npm install webpack --save-dev
 npm install webpack-cli --save-dev
npm install --save-dev webpack-dev-server
dist/index.html添加
<!doctype html>
<html>
 <head>
   <title>Getting Started</title>
 </head>
 <body>
    <script src="main.js"></script>
 </body>
</html>

package.json中添加

 "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "webpack-dev-server --open",
    "private":true
  },

创建webpack.config.js

添加
const path = require('path');
module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist')
  }
};

构建项目 npx webpack --config webpack.config.js
运行项目 npm start
在浏览器打开localhost:8080

**Comment by Ovilia** [comment]
用 `gulp` 运行就可以了

**Comment by JserJser** [comment]
> 用 `gulp` 运行就可以了
麻麻说，漂亮的女人最会骗人了。我刚刚试了一下，gulp运行，没有运行出来，哭唧唧。
![image](https://user-images.githubusercontent.com/30041386/59191151-4b481c00-8bb1-11e9-9e35-3e96dd19c9d9.png)
