### ISSUE TITLE
感觉部分颜色没有对其

### ISSUE THREAD

**Issue by birdmichael** [Ovilia/lipstick#23]
![image](https://user-images.githubusercontent.com/12954743/59906634-cfb15f00-943b-11e9-9855-0e8223473100.png)
按照笔者逻辑应该是整体背景色和当前色是匹配关系。
但是发现好多都没有对其。。
以标注为例 卡柏男孩，明显比 心跳 色调更黑，但是却在更上面。

**Comment by Ovilia** [comment]
参见 #17
